image: openjdk:8-jdk

before_script:
  - export ENV=gitlab-ci
  - chmod +x ./gradlew

stages:
  - build
  - test
  - publish

build:
  stage: build 
  script:
    - ./gradlew assemble
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
    - build/libs/
    - build/classes/

unitTests:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew test

integrationTests:
  stage: test
  dependencies:
    - build
  script:
    - ./gradlew integrationTest

publish:
  stage: publish
  only:
    - master
  dependencies:
    - build
  script:
    - ./gradlew bintrayUpload -Dbintray.user=michaelfoidl -Dbintray.key=$BINTRAY_KEY
